#cloud-config
# vim: syntax=yaml
#

# The current version of cloud-init in the Hypriot rpi-64 is 0.7.9
# When dealing with cloud-init, it is SUPER important to know the version
# I have wasted many hours creating servers to find out the module I was trying to use wasn't in the cloud-init version I had
# Documentation: http://cloudinit.readthedocs.io/en/0.7.9/index.html

# Set your hostname here, the manage_etc_hosts will update the hosts file entries as well
hostname: will-be-replaced
manage_etc_hosts: true
# don't write debian.org into apt mirrors
apt_preserve_sources_list: true

# You could modify this for your own user information
users:
  - name: msauvee
    gecos: "Mickaël Sauvée"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINRHx6QsSOif+lnWLmsqg6moeS809EAut2I58b/RNHTt mickael@sauvee.com
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEy3O/Udz84TFUB3WmiV0JEonDo+Os5085q4pKEX8ggn kylian@sauvee.com


# Update apt packages may not work (see README.md)
package_update: true
package_upgrade: true
package_reboot_if_required: true

# Set the locale of the system ... DOES NOT WORK !!!!
# locale: "fr_FR.UTF-8"

# Set the timezone
# Value of 'timezone' must exist in /usr/share/zoneinfo
timezone: "Europe/Paris"

# # WiFi connect to HotSpot
# To make wifi work with RPi3 and RPi0
# you also have to set "enable_uart=0" in config.txt
# See no-uart-config.txt for an example.
write_files:
  - content: |
      allow-hotplug wlan0
      wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
    path: /etc/network/interfaces.d/wlan0
  - content: |
      country=fr
      ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
      update_config=1
      network={
      ssid=will-be-replaced
      psk=will-be-replaced
      proto=RSN
      key_mgmt=WPA-PSK
      pairwise=CCMP
      auth_alg=OPEN
      }
    path: /etc/wpa_supplicant/wpa_supplicant.conf
  # Static IP address
  - content: |
      auto wlan0
      allow-hotplug wlan0
      iface wlan0 inet static
      address 192.168.0.9
      netmask 255.255.255.0
      gateway 192.168.0.100
      dns-nameservers 8.8.8.8 8.8.4.4
      wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
      
      auto eth0
      iface eth0 inet static
      address 192.168.0.8
      netmask 255.255.255.0
    path: /etc/network/interfaces
  # iptables/iptables/rules.v4
  - content: |
      # Generated by xtables-save v1.8.2 on Mon Jan  4 14:47:47 2021
      *nat
      :PREROUTING ACCEPT [75:15086]
      :INPUT ACCEPT [75:15086]
      :POSTROUTING ACCEPT [19:1438]
      :OUTPUT ACCEPT [19:1438]
      :DOCKER - [0:0]
      -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
      -A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
      -A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
      -A DOCKER -i docker0 -j RETURN
      COMMIT
      # Completed on Mon Jan  4 14:47:47 2021
      # Generated by xtables-save v1.8.2 on Mon Jan  4 14:47:47 2021
      *filter
      :INPUT ACCEPT [0:0]
      :FORWARD DROP [0:0]
      :OUTPUT ACCEPT [15:846]
      :DOCKER - [0:0]
      :DOCKER-ISOLATION-STAGE-1 - [0:0]
      :DOCKER-USER - [0:0]
      :DOCKER-ISOLATION-STAGE-2 - [0:0]
      :FILTERS - [0:0]
      -A INPUT -i lo -j ACCEPT
      -A INPUT -j FILTERS
      -A FORWARD -j DOCKER-USER
      -A FORWARD -j DOCKER-ISOLATION-STAGE-1
      -A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      -A FORWARD -o docker0 -j DOCKER
      -A FORWARD -i docker0 ! -o docker0 -j ACCEPT
      -A FORWARD -i docker0 -o docker0 -j ACCEPT
      -A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
      -A DOCKER-ISOLATION-STAGE-1 -j RETURN
      -A DOCKER-USER -i eno1 -j FILTERS
      -A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
      -A DOCKER-ISOLATION-STAGE-2 -j RETURN
      -A FILTERS -m state --state RELATED,ESTABLISHED -j ACCEPT
      -A FILTERS -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
      -A FILTERS -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
      -A FILTERS -s 192.168.0.0/24 -m state --state NEW -j ACCEPT
      -A FILTERS -j REJECT --reject-with icmp-host-prohibited
      COMMIT
      # Completed on Mon Jan  4 14:47:47 2021
    path: /etc/iptables/rules.v4
  # iptables/iptables/rules.v6 (block everything)
  - content: |
      *filter
      :INPUT DROP [0:0]
      :FORWARD DROP [0:0]
      :OUTPUT DROP [0:0]
      COMMIT
    path: /etc/iptables/rules.v6
  # force ipv4
  - content: |
      Acquire::ForceIPv4 "true";
    path: /etc/apt/apt.conf.d/99force-ipv4
    
mounts:
  - [ UUID=AC17-D287, /opt/data, "exfat", "defaults,auto,nofail", "0", "0" ]

# These commands will be ran once on first boot only
runcmd:
  # Pickup the hostname changes
  - systemctl restart avahi-daemon
  - echo iptables-persistent iptables-persistent/autosave_v4 boolean true | sudo debconf-set-selections
  - echo iptables-persistent iptables-persistent/autosave_v6 boolean true | sudo debconf-set-selections
  - apt-get -y install iptables-persistent
  - apt-get -y install exfat-fuse

final_message: "The system is finally up, after $UPTIME seconds"
