#cloud-config
# vim: syntax=yaml
#

# The current version of cloud-init in the Hypriot rpi-64 is 0.7.9
# When dealing with cloud-init, it is SUPER important to know the version
# I have wasted many hours creating servers to find out the module I was trying to use wasn't in the cloud-init version I had
# Documentation: http://cloudinit.readthedocs.io/en/0.7.9/index.html

# Set your hostname here, the manage_etc_hosts will update the hosts file entries as well
hostname: will-be-replaced
manage_etc_hosts: true
# don't write debian.org into apt mirrors
apt_preserve_sources_list: true

# You could modify this for your own user information
users:
  - name: msauvee
    gecos: "Mickaël Sauvée"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINRHx6QsSOif+lnWLmsqg6moeS809EAut2I58b/RNHTt mickael@sauvee.com


# Update apt packages does not work due to a problem of clock
# which lead to 'Release file for http://rasbian.raspberrypi/org/raspbian/dists/buster/InRelease is not valid yet'
package_update: false
package_upgrade: false
package_reboot_if_required: false

# Set the locale of the system ... DOES NOT WORK !!!!
# locale: "fr_FR.UTF-8"

# Set the timezone
# Value of 'timezone' must exist in /usr/share/zoneinfo
timezone: "Europe/Paris"

# # WiFi connect to HotSpot
# To make wifi work with RPi3 and RPi0
# you also have to set "enable_uart=0" in config.txt
# See no-uart-config.txt for an example.
write_files:
  - content: |
      allow-hotplug wlan0
      wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
    path: /etc/network/interfaces.d/wlan0
  - content: |
      country=fr
      ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
      update_config=1
      network={
      ssid=will-be-replaced
      psk=will-be-replaced
      proto=RSN
      key_mgmt=WPA-PSK
      pairwise=CCMP
      auth_alg=OPEN
      }
    path: /etc/wpa_supplicant/wpa_supplicant.conf
  # Static IP address
  - content: |
      auto wlan0
      allow-hotplug wlan0
      iface wlan0 inet static
      address 192.168.0.99
      netmask 255.255.255.0
      gateway 192.168.0.100
      dns-nameservers 8.8.8.8 8.8.4.4
      wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
      
      auto eth0
      iface eth0 inet static
      address 192.168.0.98
      netmask 255.255.255.0
    path: /etc/network/interfaces

mounts:
  - [ UUID=AC17-D287, /opt/data, "exfat", "defaults,auto,nofail", "0", "0" ]

# These commands will be ran once on first boot only
runcmd:
  # Pickup the hostname changes
  - 'systemctl restart avahi-daemon'
  # apt-get update/upgrade (does not work with package_update and package_upgrade)
  - apt-get update 
  - apt-get upgrade
  # install exfat-fuse for SSD
  - apt-get -y install exfat-fuse



